// Catálogo Chevrolet — datos públicos de cada modelo
// Specs verificados con fichas técnicas oficiales (Centroamérica / mercado LATAM)

export const VEHICLES = [
  {
    id: 'aveo-lt',
    nombre: 'Aveo HB LT',
    categoria: 'sedan',
    categoriaLabel: 'Hatchback',
    tagline: 'El compacto urbano',
    motor: '1.5L DOHC',
    hp: '105 HP',
    torque: '141 Nm',
    transmision: 'Manual 5 vel.',
    rendimiento: '17 km/L',
    pasajeros: '5',
    precioDesde: 'USD 17,490',
    destacado: 'Cámara reversa · Apple CarPlay · Android Auto',
    color: '#b13a3a',
    imagen: '/vehicles/aveo-hb.jpg',
  },
  {
    id: 'groove-lt',
    nombre: 'Groove LT Turbo',
    categoria: 'suv',
    categoriaLabel: 'SUV Subcompacto',
    tagline: 'SUV ágil, ciudad y carretera',
    motor: '1.5L Turbo',
    hp: '147 HP',
    torque: '230 Nm',
    transmision: 'Manual / CVT',
    rendimiento: '14 km/L',
    pasajeros: '5',
    precioDesde: 'USD 22,990',
    destacado: 'Pantalla 10.1" · 6 airbags · Sensores traseros',
    color: '#2d4d6e',
    imagen: '/vehicles/groove-lt.avif',
  },
  {
    id: 'groove-rs',
    nombre: 'Groove RS AUT',
    categoria: 'suv',
    categoriaLabel: 'SUV Subcompacto',
    tagline: 'Versión deportiva, full equipo',
    motor: '1.5L Turbo',
    hp: '147 HP',
    torque: '230 Nm',
    transmision: 'CVT Automática',
    rendimiento: '14 km/L',
    pasajeros: '5',
    precioDesde: 'USD 25,490',
    destacado: 'Rines 17" RS · Techo bitono · Detalles rojo',
    color: '#0d1117',
    imagen: '/vehicles/groove-rs.webp',
  },
  {
    id: 'captiva-lt-phev',
    nombre: 'Captiva LT PHEV',
    categoria: 'suv',
    categoriaLabel: 'SUV 7 plazas — Híbrido enchufable',
    tagline: 'Híbrido enchufable, 7 pasajeros',
    motor: '1.5L Turbo + Eléctrico',
    hp: '201 HP',
    torque: '345 Nm',
    transmision: 'eCVT',
    rendimiento: '85 km eléctricos',
    pasajeros: '7',
    precioDesde: 'USD 38,990',
    destacado: 'Modo 100% eléctrico · Carga rápida · 3 filas',
    color: '#3a4a3c',
    imagen: '/vehicles/captiva-lt.avif',
  },
  {
    id: 'captiva-premier-phev',
    nombre: 'Captiva Premier PHEV',
    categoria: 'suv',
    categoriaLabel: 'SUV 7 plazas — Premier',
    tagline: 'Tope de gama, lujo eléctrico',
    motor: '1.5L Turbo + Eléctrico',
    hp: '201 HP',
    torque: '345 Nm',
    transmision: 'eCVT',
    rendimiento: '85 km eléctricos',
    pasajeros: '7',
    precioDesde: 'USD 42,990',
    destacado: 'Cuero premium · Sunroof panorámico · ADAS',
    color: '#8b8680',
    imagen: '/vehicles/captiva-premier.avif',
  },
  {
    id: 'tracker-lt',
    nombre: 'Tracker LT',
    categoria: 'suv',
    categoriaLabel: 'SUV Compacto',
    tagline: 'El best-seller de la familia',
    motor: '1.2L Turbo',
    hp: '132 HP',
    torque: '190 Nm',
    transmision: 'Automática 6 vel.',
    rendimiento: '15 km/L',
    pasajeros: '5',
    precioDesde: 'USD 27,490',
    destacado: 'Pantalla 8" · 6 airbags · Control crucero',
    color: '#d4d0c8',
    imagen: '/vehicles/tracker-lt.avif',
  },
  {
    id: 'tracker-premier',
    nombre: 'Tracker Premier',
    categoria: 'suv',
    categoriaLabel: 'SUV Compacto — Premier',
    tagline: 'Equipamiento de lujo',
    motor: '1.2L Turbo',
    hp: '132 HP',
    torque: '190 Nm',
    transmision: 'Automática 6 vel.',
    rendimiento: '15 km/L',
    pasajeros: '5',
    precioDesde: 'USD 30,990',
    destacado: 'Cuero · Sunroof · LED · Asientos eléctricos',
    color: '#1a2530',
    imagen: '/vehicles/tracker-premier.avif',
  },
  {
    id: 'colorado-z71',
    nombre: 'Colorado Z71',
    categoria: 'pickup',
    categoriaLabel: 'Pickup Mediana 4x4',
    tagline: 'Off-road sin compromisos',
    motor: '2.7L Turbo',
    hp: '310 HP',
    torque: '583 Nm',
    transmision: 'Automática 8 vel.',
    rendimiento: '3,500 kg arrastre',
    pasajeros: '5',
    precioDesde: 'USD 49,990',
    destacado: 'Tracción 4WD · Multimatic DSSV · Hill descent',
    color: '#c25a1f',
    imagen: '/vehicles/Colorado-Z71.avif',
  },
  {
    id: 'colorado-hc',
    nombre: 'Colorado High Country',
    categoria: 'pickup',
    categoriaLabel: 'Pickup Mediana — Tope de gama',
    tagline: 'Lujo y capacidad de trabajo',
    motor: '2.7L Turbo',
    hp: '310 HP',
    torque: '583 Nm',
    transmision: 'Automática 8 vel.',
    rendimiento: '3,500 kg arrastre',
    pasajeros: '5',
    precioDesde: 'USD 54,490',
    destacado: 'Cuero premium · Bose · Heads-up · 4WD',
    color: '#2a2a2c',
    imagen: '/vehicles/Colorado-High-Country.avif',
  },
  {
    id: 'silverado-rst',
    nombre: 'Silverado RST',
    categoria: 'pickup',
    categoriaLabel: 'Pickup Full-Size',
    tagline: 'Street-ready, presencia total',
    motor: '5.3L V8 EcoTec3',
    hp: '355 HP',
    torque: '519 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '4,990 kg arrastre',
    pasajeros: '5',
    precioDesde: 'USD 62,490',
    destacado: 'Diseño negro RST · 22" rines · MyLink 13.4"',
    color: '#0a0a0b',
    imagen: '/vehicles/Silverado-RST.avif',
  },
  {
    id: 'silverado-z71',
    nombre: 'Silverado Z71',
    categoria: 'pickup',
    categoriaLabel: 'Pickup Full-Size 4x4',
    tagline: 'Trail Boss, off-road serio',
    motor: '5.3L V8 EcoTec3',
    hp: '355 HP',
    torque: '519 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '4,990 kg arrastre',
    pasajeros: '5',
    precioDesde: 'USD 66,990',
    destacado: 'Suspensión elevada · Rancho shocks · Skid plates',
    color: '#3d4a2e',
    imagen: '/vehicles/Silverado-Z71.jpg',
  },
  {
    id: 'silverado-hc',
    nombre: 'Silverado High Country',
    categoria: 'pickup',
    categoriaLabel: 'Pickup Full-Size — Tope de gama',
    tagline: 'Cuero, tecnología, capacidad',
    motor: '6.2L V8 EcoTec3',
    hp: '420 HP',
    torque: '623 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '6,123 kg arrastre',
    pasajeros: '5',
    precioDesde: 'USD 78,990',
    destacado: 'Super Cruise · Cuero perforado · Multi-Flex tailgate',
    color: '#6e3a2a',
    imagen: '/vehicles/Silverado-High-Country.avif',
  },
  {
    id: 'tahoe-rst',
    nombre: 'Tahoe RST',
    categoria: 'fullsize',
    categoriaLabel: 'SUV Full-Size',
    tagline: 'Performance edition, 7 plazas',
    motor: '5.3L V8 EcoTec3',
    hp: '355 HP',
    torque: '519 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '3,719 kg arrastre',
    pasajeros: '7',
    precioDesde: 'USD 84,990',
    destacado: 'Acabados negros · 22" RST · Magnetic Ride',
    color: '#0a0a0b',
    imagen: '/vehicles/Tahoe-RST.avif',
  },
  {
    id: 'tahoe-z71',
    nombre: 'Tahoe Z71',
    categoria: 'fullsize',
    categoriaLabel: 'SUV Full-Size 4x4',
    tagline: 'Off-road con 7 pasajeros',
    motor: '5.3L V8 EcoTec3',
    hp: '355 HP',
    torque: '519 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '3,719 kg arrastre',
    pasajeros: '7',
    precioDesde: 'USD 87,990',
    destacado: 'Skid plates · 2 vel. transfer · Hill descent · 4WD',
    color: '#4a3d2e',
    imagen: '/vehicles/Tahoe-Z71.avif',
  },
  {
    id: 'tahoe-hc',
    nombre: 'Tahoe High Country',
    categoria: 'fullsize',
    categoriaLabel: 'SUV Full-Size — Tope de gama',
    tagline: 'El máximo lujo Chevrolet',
    motor: '6.2L V8 EcoTec3',
    hp: '420 HP',
    torque: '623 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '3,719 kg arrastre',
    pasajeros: '7',
    precioDesde: 'USD 96,490',
    destacado: 'Super Cruise · Cuero · Sunroof · Bose 10-spk',
    color: '#2d3a4a',
    imagen: '/vehicles/Tahoe-High-Country.webp',
  },
  {
    id: 'suburban',
    nombre: 'Suburban',
    categoria: 'fullsize',
    categoriaLabel: 'SUV Extendido — 9 plazas',
    tagline: 'El SUV más espacioso',
    motor: '5.3L V8 EcoTec3',
    hp: '355 HP',
    torque: '519 Nm',
    transmision: 'Automática 10 vel.',
    rendimiento: '3,719 kg arrastre',
    pasajeros: '9',
    precioDesde: 'USD 91,490',
    destacado: 'Cajuela 3,447 L · 3 filas amplias · Magnetic Ride',
    color: '#3a3a3c',
    imagen: '/vehicles/Suburban.avif',
  },
];

export const CATEGORIAS = [
  { id: 'all', label: 'Todos', count: 16 },
  { id: 'sedan', label: 'Hatchback', count: 1 },
  { id: 'suv', label: 'SUV', count: 6 },
  { id: 'pickup', label: 'Pickups', count: 5 },
  { id: 'fullsize', label: 'Full-Size', count: 4 },
];
